spring.application.name=Shop
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=product_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update